### Observations

#### Observations from species file before removing rows with empty cells

There are total of 5824 entries(rows), ranging 0 to 5823

4 columns as follows:
- category
- scientific_name
- common_names
- conservation_status

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('species_info.csv')

# Data info
print(df.info())

There are 7 categories as follows:
- 1. Mammal
- 2. Bird
- 3. Reptile
- 4. Amphibian
- 5. Fish
- 6. Vascular Plant
- 7. Nonvascular Plant

In [ ]:
print("Number of Unique Categories: " + str(len(pd.unique(df['category']))))
# 7

print("Number of scientific_name: " + str(len(pd.unique(df['scientific_name']))))
# Number of scientific_name: 5541

# Species Categories list and distribution of each species category
species_categories = []

for i in range(0, len(df['category'])):
    if df['category'][i] not in species_categories:
        species_categories.append(df['category'][i])

print("Categoy list: " + str(species_categories) + "\n")
# ['Mammal', 'Bird', 'Reptile', 'Amphibian', 'Fish', 'Vascular Plant', 'Nonvascular Plant']

# List of species categories
for i in range(0, len(species_categories)):
    # print(str(i + 1) + ". " + species_categories[i])

    # Output
    # 1. Mammal
    # 2. Bird
    # 3. Reptile
    # 4. Amphibian
    # 5. Fish
    # 6. Vascular Plant
    # 7. Nonvascular Plant
    pass

Species distribution as per category is as follows:
- 1. Mammal: 214 - there are 214 species in the Mammal category
- 2. Bird: 521 - there are 521 species in the Bird category
- 3. Reptile: 79 - there are 79 species in the Reptile category
- 4. Amphibian: 80 - there are 80 species in the Amphibian category
- 5. Fish: 127 - there are 127 species in the Fish category
- 6. Vascular Plant: 4470 - there are 4470 species in the Vascular Plant category
- 7. Nonvascular Plant: 333 - there are 333 species in the Non Vascular Plant category

In [ ]:
# Occurance of species categories \ distribution
mammal = 0
bird = 0
reptile = 0
amphibian = 0
fish = 0
vascular_plant = 0
nonvascular_plant = 0

for i in range(0, len(df['category'])):
    if df['category'][i] == 'Mammal':
        mammal += 1
    elif df['category'][i] == 'Bird':
        bird += 1
    elif df['category'][i] == 'Reptile':
        reptile += 1
    elif df['category'][i] == 'Amphibian':
        amphibian += 1
    elif df['category'][i] == 'Fish':
        fish += 1
    elif df['category'][i] == 'Vascular Plant':
        vascular_plant += 1
    elif df['category'][i] == 'Nonvascular Plant':
        nonvascular_plant += 1


# print("category column length: " + str(mammal + bird + reptile + amphibian + fish + vascular_plant + nonvascular_plant))
# print("Occurance breakdown")
# print("Mammal: " + str(mammal))
# print("Bird: " + str(bird))
# print("Reptile: " + str(reptile))
# print("Amphibian: " + str(amphibian))
# print("Fish: " + str(fish))
# print("Vascular Plant: " + str(vascular_plant))
# print("Nonvascular Plant: " + str(nonvascular_plant))

# Output
# Unique Species Categories: 7
# category column length: 5824
# Occurance breakdown
# Mammal: 214
# Bird: 521
# Reptile: 79
# Amphibian: 80
# Fish: 127
# Vascular Plant: 4470
# Nonvascular Plant: 333

#### Observations after data cleanup

In [ ]:
# Remove empty rows with emptys cells
print("*********After data cleanup. After removing rows with empty cells***\n")
df.dropna(inplace = True)# modifies the original data frame

There is a total of 191 entries with conservation status

There are 4 conservation statuses indicated as follows:
- 1. Species of Concern
- 2. Endangered
- 3. Threatened
- 4. In Recovery

In [ ]:
# Lenth of conservation_status column
# print("conservation_status column entries: " + str(len(new_df['conservation_status'])))
# # 191

# Unique conservation statuses
print("Unique conservation statuses: " + str(len(pd.unique(df['conservation_status']))))
# 4

# Conservation status
conservation_statuses = []
for i in range(0, len(df['conservation_status'])):
    if df['conservation_status'].iloc[i] not in conservation_statuses:
        conservation_statuses.append(df['conservation_status'].iloc[i])

print("Conservation statuses list: " + str(conservation_statuses))
# Conservation statuses list: ['Species of Concern', 'Endangered', 'Threatened', 'In Recovery']

for i in range(0, len(conservation_statuses)):
    # print(str(i + 1) + ". " + conservation_statuses[i])
    # 1. Species of Concern
    # 2. Endangered
    # 3. Threatened
    # 4. In Recovery
    pass

Distribution of conservation statuses 
- Species of Concern: 161 - there 161 Species of Concern
- Endangered: 16 - there are 16 Endangered Species
- Threatened: 10 - there are 10 Threatened Species
- In Recovery: 4 - there are  Species In Recovery

The following are endangered species: Mammal, Bird, Fish, Vascular Plant, Amphibian (making a total of 16 endangered species) as shown below:
- 7 Endangered mammals - mammals are the most endangered species
- 4 Endangered birds
- 3 Endangered fishes
- 1 Endangered Vascular Plants
- 1 Endangered amphibians

In [ ]:
# Conservation statuses
species_of_concern = 0
endangered = 0
threatened = 0
in_recovery = 0

endangered_species = [] # list
endangered_species_cnt = 0 # counter

endangered_mammals = 0
endangered_birds = 0
endangered_reptile = 0
endangered_fishes = 0
endangered_amphibians = 0
endangered_vascular_plants = 0
endangered_nonvascular_plants = 0

in_recovery_mammals = 0
in_recovery_birds = 0
in_recovery_reptile = 0
in_recovery_fishes = 0
in_recovery_amphibians = 0
in_recovery_vascular_plants = 0
in_recovery_nonvascular_plants = 0

threatened_mammals = 0
threatened_birds = 0
threatened_reptile = 0
threatened_fishes = 0
threatened_amphibians = 0
threatened_vascular_plants = 0
threatened_nonvascular_plants = 0

for i in range(0, len(df['conservation_status'])):
    if df['conservation_status'].iloc[i] == 'Species of Concern':
        species_of_concern += 1
    elif df['conservation_status'].iloc[i] == 'Endangered':
        endangered += 1
        if df['category'].iloc[i] == 'Mammal':
            endangered_mammals += 1
        elif df['category'].iloc[i] == 'Bird':
            endangered_birds += 1
        elif df['category'].iloc[i] == 'Reptile':
            endangered_reptile += 1
        elif df['category'].iloc[i] == 'Fish':
            endangered_fishes += 1
        elif df['category'].iloc[i] == 'Vascular Plant':
            endangered_vascular_plants += 1
        elif df['category'].iloc[i] == 'Nonvascular Plant':
            endangered_nonvascular_plants += 1
        elif df['category'].iloc[i] == 'Amphibian':
            endangered_amphibians += 1

        if df['category'].iloc[i] not in endangered_species:
            endangered_species_cnt += 1
            endangered_species.append(df['category'].iloc[i])
    elif df['conservation_status'].iloc[i] == 'Threatened':
        threatened += 1
        if df['category'].iloc[i] == 'Mammal':
            threatened_mammals += 1
        elif df['category'].iloc[i] == 'Bird':
            threatened_birds += 1
        elif df['category'].iloc[i] == 'Reptile':
            threatened_reptile += 1
        elif df['category'].iloc[i] == 'Fish':
            threatened_fishes += 1
        elif df['category'].iloc[i] == 'Vascular Plant':
            threatened_vascular_plants += 1
        elif df['category'].iloc[i] == 'Nonvascular Plant':
            threatened_nonvascular_plants += 1
        elif df['category'].iloc[i] == 'Amphibian':
            threatened_amphibians += 1
    elif df['conservation_status'].iloc[i] == 'In Recovery':
        in_recovery += 1
        if df['category'].iloc[i] == 'Mammal':
            in_recovery_mammals += 1
        elif df['category'].iloc[i] == 'Bird':
            in_recovery_birds += 1
        elif df['category'].iloc[i] == 'Reptile':
            in_recovery_reptile += 1
        elif df['category'].iloc[i] == 'Fish':
            in_recovery_fishes += 1
        elif df['category'].iloc[i] == 'Vascular Plant':
            in_recovery_vascular_plants += 1
        elif df['category'].iloc[i] == 'Nonvascular Plant':
            in_recovery_nonvascular_plants += 1
        elif df['category'].iloc[i] == 'Amphibian':
            in_recovery_amphibians += 1

# print(species_of_concern + endangered + threatened + in_recovery)
# 191

print("Species of Concern: " + str(species_of_concern))
print("Endangered: " + str(endangered))
print("Threatened: " + str(threatened))
print("In Recovery: " + str(in_recovery))

# Output
# Species of Concern: 161
# Endangered: 16
# Threatened: 10
# In Recovery: 4

# print("Endangered species count: " + str(len(endangered_species)))
# 5

# print("Endangered species categories: " + str(endangered_species)) 
# ['Mammal', 'Bird', 'Fish', 'Vascular Plant', 'Amphibian']

# Endangered species distribution
print(str(endangered_mammals) + " Endangered mammals") # 7 Endangered mammals
print(str(endangered_birds) + " Endangered birds") # 4 Endangered birds
print(str(endangered_reptile) + " Endangered reptiles") # 0 Endangered reptiles
print(str(endangered_fishes) + " Endangered fishes") # 3 Endangered fishes
print(str(endangered_vascular_plants) + " Endangered Vascular Plants") # 1 Endangered Vascular Plants
print(str(endangered_nonvascular_plants) + " Endangered NonVascular Plants") # 0 Endangered NonVascular Plants
print(str(endangered_amphibians) + " Endangered amphibians") # 1 Endangered amphibians

# In recovery species distribution
print(str(in_recovery_mammals) + " mammals in recovery") # 1 mammals in recovery
print(str(in_recovery_birds) + " birds in recovery") # 3 birds in recovery
print(str(in_recovery_reptile) + " reptiles in recovery") # 0 reptiles in recovery
print(str(in_recovery_fishes) + " fishes in recovery") # 0 fishes in recovery
print(str(in_recovery_vascular_plants) + " Vascular Plants in recovery") # 0 Vascular Plants in recovery
print(str(in_recovery_nonvascular_plants) + " NonVascular Plants in recovery") # 0 NonVascular Plants in recovery
print(str(in_recovery_amphibians) + " amphibians in recovery") # 0 amphibians in recovery

# Threatened species distribution
print(str(threatened_mammals) + " threatened mammals") # 2 threatened mammals
print(str(threatened_birds) + " threatened birds") # 0 threatened birds
print(str(threatened_reptile) + " threatened reptiles") # 0 threatened reptiles
print(str(threatened_fishes) + " threatened fishes") # 4 threatened fishes
print(str(threatened_vascular_plants) + " threatened Vascular Plants") # 2 threatened Vascular Plants
print(str(threatened_nonvascular_plants) + " threatened NonVascular Plants") # 0 threatened NonVascular Plants
print(str(threatened_amphibians) + " threatened amphibians") # 2 threatened amphibians

# Occurance of varous categories after clean up
mammal_clean = 0
bird_clean = 0
reptile_clean = 0
amphibian_clean = 0
fish_clean = 0
vascular_plant_clean = 0
nonvascular_plant_clean = 0


for i in range(0, len(df['category'])):
    if df['category'].iloc[i] == 'Mammal':
        mammal_clean += 1
    elif df['category'].iloc[i] == 'Bird':
        bird_clean += 1
    elif df['category'].iloc[i] == 'Reptile':
        reptile_clean += 1
    elif df['category'].iloc[i] == 'Amphibian':
        amphibian_clean += 1
    elif df['category'].iloc[i] == 'Fish':
        fish_clean += 1
    elif df['category'].iloc[i] == 'Vascular Plant':
        vascular_plant_clean += 1
    elif df['category'].iloc[i] == 'Nonvascular Plant':
        nonvascular_plant_clean += 1


print("category column length: " + str(mammal_clean + bird_clean + reptile_clean + amphibian_clean + fish_clean + vascular_plant_clean + nonvascular_plant_clean))
print("Summary breakdown")
print("Mammal: " + str(mammal_clean))
print("Bird: " + str(bird_clean))
print("Reptile: " + str(reptile_clean))
print("Amphibian: " + str(amphibian_clean))
print("Fish: " + str(fish_clean))
print("Vascular Plant: " + str(vascular_plant_clean))
print("Nonvascular Plant: " + str(nonvascular_plant_clean))

# Output
# 191
# Mammal: 38
# Bird: 79
# Reptile: 5
# Amphibian: 7
# Fish: 11
# Vascular Plant: 46
# Nonvascular Plant: 5

#### Observations from observations file

There are 23296 entries, ranging from 0 to 23295

In [ ]:
df1 = pd.read_csv('observations.csv')

print(df1.info())

There are 4 parks as follows:
- 1. Great Smoky Mountains National Park
- 2. Yosemite National Park
- 3. Bryce National Park
- 4. Yellowstone National Park

Entry distribution as per park
- Great Smoky Mountains National Park: 5824
- Yosemite National Park: 5824
- Bryce National Park: 5824
- Yellowstone National Park: 5824

There are 5541 unique scientific names spread accross the 4 different parks

Total number of observation in the farks for the 7 days: 3314739

In [ ]:
print("Number of parks: " + str(len(pd.unique(df1['park_name'])))) # Unique parks
# 4

park_names_list = []

for i in range(0, len(df1['park_name'])):
    if df1['park_name'][i] not in park_names_list:
        park_names_list.append(df1['park_name'][i])

# print(park_names_list)
# ['Great Smoky Mountains National Park', 'Yosemite National Park', 'Bryce National Park', 'Yellowstone National Park']

for i in range(0, len(park_names_list)):
    # print(str( i + 1) + ". " + park_names_list[i])
    # Output
    # 1. Great Smoky Mountains National Park
    # 2. Yosemite National Park
    # 3. Bryce National Park
    # 4. Yellowstone National Park
    pass

# Parks distribution
great_smoky_park = 0
yosemite_national_park = 0
bryce_national_park = 0
yellowstone_national_park = 0

for i in range(0, len(df1['park_name'])):
    if df1['park_name'][i] == 'Great Smoky Mountains National Park':
        great_smoky_park += 1
    elif df1['park_name'][i] == 'Yosemite National Park':
        yosemite_national_park +=1
    elif df1['park_name'][i] == 'Bryce National Park':
        bryce_national_park += 1
    elif df1['park_name'][i] == 'Yellowstone National Park':
        yellowstone_national_park += 1


print("Great Smoky Mountains National Park -> " + str(great_smoky_park) + " entries of species") # 5824
print("Yosemite National Park -> " + str(great_smoky_park) + " entries of species") # 5824
print("Bryce National Park -> " + str(bryce_national_park) + " entries of species") # 5824
print("Yellowstone National Park -> " + str(yellowstone_national_park) + " entries of species") # 5824

print("Number of scientific_name: " + str(len(pd.unique(df1['scientific_name'])))) # 5541